#!/usr/bin/env python
# -*- coding: utf-8 -*-

#Valor da coca-cola é 45 centavos
#aceita apenas moedas de 25 e 10 centavos
#Não tem troco (não devolve moedas inseridas)

coca = 0.45
valor = 0.0

print("\n\n---O preço da Coca é R$0,45---")
print("---Insira o valor em centavos---\n\n")


while(valor<coca):

moeda= float(input('Insira uma moeda\n\t'))
moeda /= 100

if (moeda==0.25) or (moeda==0.1):
valor += moeda
round(valor,2)
print("\n\nValor já inserido:", round(valor,2))

else:
print("\n----Só aceitamos moedas equivalente a R$0,25 e R$0,10 centavos---")
print("---Ops, algo deu errado, não devolvemos dinheiro!---\n\n")

if (valor==0.45):
print("\n\n\n\t\tOperação finalizada!!! Você adquiriu uma coca por 45 centavos")
else:
print("\n\n\n\t\tVocê adquiriu sua coca por %s reais. Não devolveremos troco!"% valor)
